version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-net
    volumes:
       - db-data:/data/db


  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
    restart: unless-stopped
    networks:
      - app-net

#  flaskapp:
#    build: ./Dockerfile1
##    command: flask run --host 0.0.0.0 --port 5000
#    ports:
#      - '8000:8000'
#    depends_on:
#      - "mongodb"
#    networks:
#      - app-net
#    restart: always
#    stdin_open: true
#    tty: true


networks:
  app-net:
    driver: bridge

volumes:
  - db-data:
